### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by peter279k** [jason-napolitano/PHP-Exceptions#1]
As title, I think we can integrate CI service.

And this work can let every upcoming PRs and commits do tests automatically.

**Comment by jason-napolitano** [comment]
@peter279k I too think this is a great idea and will be looking into it shortly. I am not too familiar with CI yet and want to make sure I am well versed in it.

**Comment by peter279k** [comment]
Hi @jason-napolitano, thanks for your concern.

This PR I can help you and you can assign me to be a collaborator if possible :).

**Comment by jason-napolitano** [comment]
Invitation sent. Thank you for your interest. I have some pretty neat plans of actually converting this into a full PHP exception framework, and you're more than welcome to join =)

**Comment by jason-napolitano** [comment]
I've started the CI process (f6c8181) =D

**Comment by jason-napolitano** [comment]
I've started the [`Travis CI`](https://travis-ci.com/jason-napolitano/PHP-Exceptions) process but I fully admit that I do not know what I am doing lol. I believe I get the gist of it but still have a lot to learn.

**Comment by peter279k** [comment]
@jason-napolitano, that's great.

If you've already initialized the Travis CI build, you can just send the PR.

And I can review this and suggest some recommendations :).

**Comment by peter279k** [comment]
Ok. I see that it has the Travis CI build now.

I will enhance them and send the PR.

Thanks for your initialized effort, @jason-napolitano 💪 !

**Comment by jason-napolitano** [comment]
Thanks for anything you may like to offer =)

Since my knowledge in CI is still so minimal, it took me a while to get things going through trial-and-error, but I believe I've got the hang of it now. The nightly PHP build does not get satisfied due to PHPUnit ^8, so I left it at PHP 7.3 in the interim in the `.travis.yml` file.
