### ISSUE TITLE
Add new exceptions

### ISSUE THREAD

**Issue by jason-napolitano** [jason-napolitano/PHP-Exceptions#5]
This issue is open to remind me to add the following exceptions by the [1.0.0 milestone](https://github.com/jason-napolitano/PHP-Exceptions/milestone/1).

  - `\Exceptions\Authentication\*`
  - `\Exceptions\Authorization\*`
  - `\Exceptions\Encryption\*`
  - Add tests for the above

**Comment by peter279k** [comment]
I think  the HTTP exception can split to other related HTTP exceptions.

And they can also map to the HTTP status codes and response messages.

The related HTTP exceptions are as follows:

- `ConnectException`
- `RequestException`
- `ResponseException`
- `ServerException`
- `TooManyRedirectException`
and etc.

## References
- https://github.com/guzzle/guzzle/tree/master/src/Exception

@jason-napolitano, what do you think about this?

**Comment by jason-napolitano** [comment]
I think that's exactly how it should be done. I like your idea of looking at Guzzle. I believe that a PSR-7 style structure should be implemented if possible too. Also, it is a great idea to map the status codes as well. If you'd like to submit a PR that'd be sweet, if not I'm going to try to get to this today or tomorrow for sure.

Thanks again!

**Comment by peter279k** [comment]
@jason-napolitano, I can create related PR about HTTP exceptions.

Thanks for your concern again!

**Comment by jason-napolitano** [comment]
Thank you! That'd be awesome=)

**Comment by peter279k** [comment]
Just notice that the HTTP status codes:

- 1×× Informational
- 2×× Success
- 3×× Redirection
- 4×× Client Error * 400 Bad Request * 401 Unauthorized ... * 405 Method Not Allowed ...
- 5×× Server Error * 500 Internal Server Error * 501 Not Implemented * 502 Bad Gateway ...

I think the error exceptions are about the `ClientException` and `ServerException`.

I think we can consider adding the `ClientException` and `ServerException` classes.

**Comment by peter279k** [comment]
The `ClientException` class seems to be done via PR #10.
