### ISSUE TITLE
Overhaul test suites

### ISSUE THREAD

**Issue by jason-napolitano** [jason-napolitano/PHP-Exceptions#8]
So, I want to better separate current test components. I have started to implement a new strategy for future tests to follow, as seen in 920b6fb and e744669. This strategy is: a single test per exception class. This issue was opened to remind me to finish by the [1.0.0 milestone](https://github.com/jason-napolitano/PHP-Exceptions/milestone/1)

**TODO LIST**
 - [x] `\Tests\Authentication`
 - [x] `\Tests\FileSystem`
 - [x] `\Tests\Collection`
 - [x] `\Tests\Operation`
 - [x] `\Tests\Helpers`
 - [ ] `\Tests\HTTP`
 - [ ] `\Tests\Intl`
 - [ ] `\Tests`

**Comment by peter279k** [comment]
Hi @jason-napolitano, thanks for your reply.

It seems that you want to separate the tests to per exception class.

It's easy for us to track the tests and focus on the single Exception class :muscle:.

**Comment by jason-napolitano** [comment]
This is m thought exactly @peter279k =). 

Easier all the way around, from development to testing. Plus, it is a far more consistent nomenclature between tests and actual exception classes within the library. I also plan on soon including this stipulation in the work-in-progress [`CONTRIBUTING.md`](https://github.com/jason-napolitano/PHP-Exceptions/blob/master/CONTRIBUTING.md) file as well.

Thanks!

**Comment by peter279k** [comment]
Hi @jason-napolitano, thanks for your reply.

If possible, you can also send the one PR to per issue.

It can also help us to track every issue via one PR and it's easy for us to review every changes.

**Comment by jason-napolitano** [comment]
Yes, this is a great idea. I will add more verbose instruction sets later today and this will be implemented =)

Thank you again!

**Comment by jason-napolitano** [comment]
Added to `CONTRIBUTING.md` here 2c18521 @peter279k =)

**Comment by peter279k** [comment]
> Added to `CONTRIBUTING.md` here [2c18521](https://github.com/jason-napolitano/PHP-Exceptions/commit/2c185211a35bc59e75a42f87923e8a62e8c47ca0) @peter279k =)

@jason-napolitano, I think we can consider integrating the `PHP_CondeSniffer` or `php-cs-fixer` to check the PSR-2 coding style during the CI build.

What do you think?

**Comment by jason-napolitano** [comment]
I think that's great. I have PHP CodeSniffer in the `require-dev` of `composer.json`, which I use on pre-commit. I am thinking about adding it to the Travis build too. But ultimately yes, this needs to be done  with `php-cs`fixer` as well =)
